version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pg_inmobiliaria
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inmobiliaria_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
